### PR TITLE
Fix some typo

### PR DESCRIPTION
**Pull request by Gustry**
There is an `INSTALL` file anymore in the repository.

What is the best way to have the website running locally ? (cc @dimasciput ?)

### CODE REVIEW

**Comment by sumandari** [comment]
@Gustry @dimasciput 
I have had it running in my local machine :

1.  Go to dockerize directory
`cd dockerize`

2. Build and spin docker-compose
```
docker-compose build
docker-compose up -d
```

> If you got an error bellow:
> `ERROR: for qgis-plugins-devweb  Cannot start service devweb: Cannot link to a non running container: /qgis-plugins-worker AS /qgis-plugins-devweb/qgis-plugins-worker`
> change the celery version in ./dockerize/docker/REQUIREMENTS.txt to `celery==4.3.1`
> build and spin docker-compose again

3. Run migrate in web container
`docker-compose exec web python manage.py migrate`

4. To run development version, set up python interpreter in PyCharm or just runserver from devweb container:
`docker-compose exec devweb python manage.py runserver 0.0.0.0:8080`
and now, you can see your site at `http://0.0.0.0:62202`

**Comment by Gustry** [comment]
Thanks for these notes. Can you add them in a INSTALL.md file somewhere?

**Comment by timlinux** [comment]
@sumandari ping on this - can you update the INSTALL please?

**Comment by sumandari** [comment]
@timlinux would you please review https://github.com/qgis/QGIS-Django/pull/89. Thank you.

**Pull request merged**
