### PR TITLE
GH Action - Review the CI action about some python flake

### PR DESCRIPTION
**Pull request by Gustry**
Somehow, the flake8 check on the CI was not really checking the code.
To have flake8 happy on my local, I had to disable a few checks written in the file above.

The CI is happy with this.

Let's disable some of them step by step

### CODE REVIEW

**Comment by Gustry** [comment]
@dimasciput and @sumandari Can you have a look to this PR ? Thanks

**Comment by sumandari** [comment]
Hi, Thanks @Gustry! 
apologize for the delay, I was asking you a question about the change in `setup.cfg` file why there are many in the ignored list since on my local I got them checked (flake8 --version
3.7.9 (mccabe: 0.6.1, pycodestyle: 2.5.0, pyflakes: 2.1.1) CPython 3.8.10 on Linux).
But now I saw the comment on the line, and it looks good to me

**Review by sumandari — APPROVED** [review]

**Comment by sumandari** [comment]
Thanks again @Gustry for your work. I learned things from your changes, I will merge it for now.

**Comment by Gustry** [comment]
@sumandari Maybe before the path was not well configured ?
I got all these python warnings/errors when running flake8 on my local.
If I uncomment one of them, I will have it in the error list.

**Comment by sumandari** [comment]
um, I'm not sure about this :sweat_smile:. I didn't see any error on my local. But this changes also fine on my local. So I don't think there will be any further issue.
> @sumandari Maybe before the path was not well configured ?

**Pull request merged**
