### PR TITLE
Display latest plugin version on plugins list data table

### PR DESCRIPTION
**Pull request by sumandari**
@timlinux @dimasciput 

This PR refers to #82. It does:
- show latest plugins version in  list view
- enable sort by latest version in plugins list table

/cc @agiudiceandrea

plugins_ticket82_pr_fig3

plugins_82_latest_version

### CODE REVIEW

**Comment by sumandari** [comment]
update PR based on https://github.com/qgis/QGIS-Django/issues/82#issuecomment-734983009

- fresh plugins list contains new plugins
- latest plugins list contains new plugins + new version uploaded

plugins_82_latest_fresh

**Comment by timlinux** [comment]
I think we should change the word 'Fresh' to 'New Plugins' and we can rename 'Updated' to 'Updated Plugins' to make things really clear.

**Comment by timlinux** [comment]
LGTM after above tweak applied.

**Review by dimasciput — APPROVED** [review]
LGTM @sumandari

**Comment by agiudiceandrea** [comment]
Hi @sumandari, thanks for your fix!
Anyway I wonder why there are only 4 plugins listed in the "New plugins" list
image

**Comment by sumandari** [comment]
Hello @agiudiceandrea, both list (New plugins and Updated plugins) are using the same logic with Fresh plugins (the previous replaced one). It only shows  plugins created/updated within 7 days.

**Comment by agiudiceandrea** [comment]
It's strange... the "New plugins" list only lists 4 plugins with the "Created on" attribute that spans between Dec. 4, 2020 and Dec. 1, 2020, while the "Updated plugins" list lists 68 plugins with the "Latest Plugin Version" attribute that spans between today and June 29, 2012 (!).

Moreover, looking better at the "Updated plugins" list, it seems that something weird also happens in this list.
If you look at the second and subsequent pages, a lot of updated plugins are missing:
Neural Network MLPClassifier, MESMA, Tree Density Calculator (latest version Nov. 29, 2020)
KP Find, Area Ratio, Configurable search, thematics, Geomapfish Locator, ValueMap to Lizmap (Nov. 27, 2020)
MapBiomas Collection, TUFLOW (Nov. 26, 2020)
Data-Driven Input Mask (Nov. 25, 2020)
PAT - Precision Agriculture Tools, EO Time Series Viewer, MSDC Client, Wtyczka GIS Support (Nov. 24, 2020)
and so on...

**Comment by sumandari** [comment]
thanks for looking into this @agiudiceandrea.

New plugins and Updated plugins has different datetime field to filter in queryset

`new plugins` is plugins created_on within 7 days
https://github.com/qgis/QGIS-Django/blob/fde67d7b80b832541c226d46813c25b13ee54dd4/qgis-app/plugins/models.py#L96

meanwhile `updated plugins` is plugins `modified_on` within 7 days
https://github.com/qgis/QGIS-Django/blob/fde67d7b80b832541c226d46813c25b13ee54dd4/qgis-app/plugins/models.py#L114

when I wrote this, the last object in last page of `updated plugins` list is 
82_latest_fresh_2
the modified_on value of this plugins is
```
 2020-12-02 04:43:12.362557+00

```

**Comment by agiudiceandrea** [comment]
Hi @sumandari, thanks for looking at this.

I thought PLUGINS_FRESH_DAYS = 30 days as stated in https://github.com/qgis/QGIS-Django/blob/master/qgis-app/plugins/docs/introduction.rst. I think 30 days would be better then 7 days for both "**New plugins**" and "**Updated plugins**" lists.

Anyway as previously said, I think the problem for "**Updated plugins**" list is that, from a user perspective, probably is not useful to use the modified_on attribute to filter the items.
"**Updated plugins**" list is now sorted by `latest_version_date`, so it could be better to use `latest_version_date` instead of `modified_on` (it is not really clear to me what the `modified_on` date refers to and when and in which cases it is updated).
Otherwise, the Updated plugins list weirdly lists, as now lists, a plugin whose last version was uploaded in 2012, while it not lists plugins updated some days ago...

**Comment by sumandari** [comment]
Thanks for your input @agiudiceandrea, I submitted PR for fixing it. Please kindly look at https://github.com/qgis/QGIS-Django/pull/136.

**Pull request merged**
