### PR TITLE
Fix multiple tags issue in plugin upload

### PR DESCRIPTION
**Pull request by dimasciput**
The issue was caused by improper handling of multiple tags during the upload process.
Also added test to check the upload with multiple tags.

### CODE REVIEW

**Comment by Guts** [comment]
Is this issue causing this plugin publication: https://github.com/Guts/qgis-plugin-resource-browser/actions/runs/4758013982/jobs/8455540814#step:9:21?

**Comment by agiudiceandrea** [comment]
@dimasciput @timlinux, is thi issue actually fixed? See https://lists.osgeo.org/pipermail/qgis-developer/2023-April/065754.html

**Comment by dimasciput** [comment]
@agiudiceandrea thanks for the report, will check this again.

**Comment by dimasciput** [comment]
@agiudiceandrea the issue was because the tag library was outdated. I have updated it, and it should be working now.

**Comment by agiudiceandrea** [comment]
Thanks @dimasciput !

**Pull request merged**
