### PR TITLE
Restructure settings configuration and dockerize deployment for production, staging, and development

### PR DESCRIPTION
**Pull request by akbargumbira**
Hi @elpaso and @timlinux, this PR contains:
- Restructuring settings configuration in core.settings to make deployment and development easier. I still keep the settings.py, settings_auth.py, and settings_local.py modules in the qgis-app (will remove it if you think it's not necessary anymore).
- Adding support for docker deployment (for production, staging, and development) and nice stuffs like daily backups (@timlinux's stuffs). See deployment directory. There is also a template for deploying this for staging and production using nginx on the host (deployment/qgis-django.nginx.conf and deployment/qgis-django-staging.nginx.conf). I still keep the apache dir in case you still prefer to use it.

For the deployment, if after you run _make deploy_, you find some problems related to database or contenttype, please run _make deployment_ again. As the data is persistent and mounted to the deployment dir, spinning up the db container takes a while, meanwhile other containers already try to use it. Once docker compose could delay container startup, this should be fixed (https://github.com/docker/compose/issues/374)

If you still prefer to deploy/develop it in a non-docker environment, you can still use the current way (making virtualenv and do other stuffs in that venv)

### CODE REVIEW

**Comment by akbargumbira** [comment]
My next plan would be:
- Pipelining resources
- Updating user map to use django-user-map
- Look at the styles, symbols, and templates repository that was done by gsoc some time ago

**Comment by elpaso** [comment]
Great job! Thanks. 
I'm leaving for FOSS4G Europe and next I'll be on vacation until end of july, I'm sorry but I'll have no time to test your PR in the next weeks.

**Comment by akbargumbira** [comment]
No rush @elpaso, in the meantime, I will do the resources pipelining in this PR

**Comment by akbargumbira** [comment]
Hi @timlinux and @elpaso. I just looked at this again and added some fixtures for development environemt. Development attaches the production containers, so to run development, you can do:
- go to /deployment
- run ```make deploy```. Repeat this command if there's error related to db until there's no error (I mentioned above that there is no way to delay container startup in docker compose).
- run ```make dev-run```. This will load some fixtures e.g simplemenu, flatpages, auth (there are 3 users: staff (password: staff), creator (creator), admin (admin).

**Comment by timlinux** [comment]
@sumandari can you please review this and see if there is anything still usable here, then pull that out and apply, otherwise let's close this as stale.

**Comment by sumandari** [comment]
noted @timlinux. I will review it

**Comment by akbargumbira** [comment]
6 years later :)

**Comment by lucernae** [comment]
Welcome back @akbargumbira . Hahaha

**Comment by sumandari** [comment]
@akbargumbira thank you for your works!
We are sorry for very late review :blush: . 
Currently we have already implemented dockerize deployment and updated lots of libraries. 
So that we will close it as stale.

**Pull request closed without merging**
