### PR TITLE
Add support for renaming plugin package_name

### PR DESCRIPTION
**Pull request by dimasciput**
This is for https://github.com/qgis/QGIS-Django/issues/270

### CODE REVIEW

**Comment by Gustry** [comment]
I'm not sure to understand, is-it a feature to update the plugin name ?

Did you try to check the behavior in QGIS desktop ?
Like : 

1. Install plugin X in QGIS desktop
2. The plugin X is renamed to plugin Y
3. What happen in QGIS desktop ? Does plugin Y detected as not installed ?

Sorry if it's not related and skip my comment :)

Edit : 
Sorry, I just checked after writing this comment, the issue #270 ...

**Comment by Gustry** [comment]
Ok thanks for the information. You can still press the "convert to draft" ;-)

There are few things to check indeed for allowing this ticket. I'm not sure how you want to proceed on the desktop side.

**Comment by PeterPetrik** [comment]
It would be enough for this time to keep (old) plugin identifier (directory name) and only change human readable name, likely with no changes in qgis desktop. Renaming would effectively forcing new human readable name. 

Human readable name should be used in QGIS installer, and also on qgis plugin site in title of the plugin/list of plugins. Important is to now override this human readable name on new plugin version upload (as zip) - this name should be configurable ideally as plugin admin/owner in the part where you upload new plugin version. It would be even enough it it is not modifiable by user/owner , just by some super-admin (e.g. need to write mail to Tim to change the name for us)

Screenshot 2023-11-03 at 11 03 06

Thanks a lot!

**Comment by timlinux** [comment]
Thanks @PeterPetrik . @Xpirix when you take over the original ticket and this PR it might be good to write up a clear design for @PeterPetrik and @Gustry to comment on before you start building stuff, taking special care to understand and document the impacts in the QGIS desktop environment.

**Comment by Xpirix** [comment]
Thanks @timlinux . That is well noted.

**Comment by Xpirix** [comment]
@PeterPetrik @Gustry @timlinux Please find below my understanding of the ticket and the PR. 

- ### Plugin Renaming:
	- **Django Admin Update**: the field `name` of the model `Plugins` will be editable by a Super admin
	- **Plugin Version Upload**: Allow the `name` field to be part of the form when uploading a new plugin version, enabling admins or owners to rename it during this process.
	- **Renaming Without New Version**: If the owner wishes to rename a plugin without uploading a new version, they can request the change from a super-admin via the admin page.
- ### Impacts on Plugin Website and QGIS:
	- **QGIS Plugin Site**: Changing the plugin name will directly affect the plugin title both in the plugin list and on the plugin's page on the QGIS plugin site.
	- **QGIS Application**: The modified name will reflect in the plugin installer window in QGIS, even if the plugin is already installed. However, to view these changes, it is necessary to fetch repositories.
- ### Changing the  `package_name` :
	- It's advisable to maintain the old plugin identifier (directory name) to avoid issues.
	- When the `package_name` changes, QGIS might detect the plugin as not installed, potentially resulting in an error during installation.

Please feel free to comment if you have any concerns about this.

**Comment by PeterPetrik** [comment]
Looks good to me, maybe @wonder-sk can comment too?

**Comment by wonder-sk** [comment]
Looks good to me as well. I agree that it is best not to allow modification of package name (at least for now) as this would introduce issues on the client side related to the renaming and how to smoothly handle the transition.

**Comment by Xpirix** [comment]
Thanks @PeterPetrik @wonder-sk . Please find below the new PR: 

- #302

**Pull request closed without merging**
