### PR TITLE
Admin setting to manage qgis version

### LINKED ISSUE #237: We need an admin UI for managing versions
Currently the QGIS versions list is maintained here

imagem

https://github.com/qgis/QGIS-Django/blob/aa91b575f4920b78e74f176a306fbf4963c0c3ed/qgis-app/plugins/tasks/generate_plugins_xml.py#L21

Which is very fragile and manual, requiring a developer to update code and redeploy the site each time a new version of QGIS is released. Can we make an admin UI for doing this. It would still be manual but at least will not require code changes etc. to update.

### PR DESCRIPTION
**Pull request by dimasciput**
To fix https://github.com/qgis/QGIS-Django/issues/237

### CODE REVIEW

**Comment by agiudiceandrea** [comment]
3.32 and 3.33 missing... see: https://github.com/qgis/QGIS/issues/53568.

**Comment by dimasciput** [comment]
@agiudiceandrea, if you have admin access, you can add the version here: https://plugins.qgis.org/admin/preferences/sitepreference/2/change/

I've just added them. The system will generate those two versions within an hour.

**Comment by agiudiceandrea** [comment]
I don't have admin access.

**Comment by Gustry** [comment]
Great this new PR.

I just did for 3.34 and 3.35, let's see.

**Comment by agiudiceandrea** [comment]
Thanks @Gustry! It would be great if the versions were added just before each new release: see https://github.com/qgis/QGIS/issues/55077.

**Comment by simonkam** [comment]
Missing 3.40.5

**Comment by agiudiceandrea** [comment]
> Missing 3.40.5

@simonkam , what do tuo mean exactly?

**Pull request merged**
