### PR TITLE
Fix xml <update_date>

### LINKED ISSUE #188: <update_date> field is always empty for all plugins in plugins.xml
This breaks the "Sort by Date Updated" functionality introduced with https://github.com/qgis/QGIS/pull/35008 in the QGIS plugins manager.
See https://github.com/qgis/QGIS/issues/44810

### PR DESCRIPTION
**Pull request by sumandari**
To fix #188 

```
$ curl 'http://localhost:62202/plugins/plugins.xml?qgis=3.20' | grep update_date -B 1

 <create_date>2019-05-30T14:27:48.790339</create_date>
 <update_date>2021-06-23T00:32:26.459623</update_date>
```

### CODE REVIEW

**Comment by dimasciput** [comment]
LGTM thanks @sumandari

**Comment by suricactus** [comment]
@sumandari thanks for the fix!

**Comment by agiudiceandrea** [comment]
@sumandari @suricactus it seems there is something wrong with the dates in plugins.xml compared with the dates displayed in plugins.qgis.org.
Just some example:
- Mapflow
  - plugins.xml
<create_date>2021-09-29T09:23:12.996709</create_date>
<update_date>2021-09-29T09:23:13.225389</update_date>
  - plugins.qgis.org
Created on: July 9, 2021
Latest Plugin Version: Sept. 29, 2021

- ImportPhotos
  - plugins.xml
<create_date>2021-09-29T08:02:29.323220</create_date>
<update_date>2021-09-30T00:33:46.533987</update_date>
  - plugins.qgis.org
Created on: Feb. 16, 2018
Latest Plugin Version: Sept. 29, 2021

- OpenLayers Plugin
  - plugins.xml
<create_date>2018-04-09T06:39:24.116894</create_date>
<update_date>2021-09-25T10:25:28.166562</update_date>
  - plugins.qgis.org
Created on: Oct. 4, 2012
Latest Plugin Version: April 9, 2018

- QuickMapServices
  - plugins.xml
<create_date>2021-08-24T09:38:22.559787</create_date>
<update_date>2021-09-28T11:11:48.735641</update_date>
  - plugins.qgis.org
Created on: Jan. 11, 2015
Latest Plugin Version: Aug. 24, 2021

**Comment by sumandari** [comment]
Hi @agiudiceandrea thank you for your report

the one show in the plugins website shows the plugin created date (first version) and plugin latest version created_on

on the XML
created date = latest version created_on
update date = plugin last modified

could you please advise which value we want to get in the XML? cc @suricactus

**Comment by agiudiceandrea** [comment]
In my opinion it is obvious that it should be like this:

XML create_date = the date on which the plugin was created (i.e. the date when was uploaded for the first time) = "Created on" date on plugins.qgis.org

XML update_date = the date on which the plugin was updated (i.e. the date when the latest version available was uploaded) = "Latest Plugin Version" date on plugins.qgis.org

**Comment by suricactus** [comment]
Please note that the `updated_at` from django is the date when the plugin info (the Django model) was updated, not the date of the latest version. This is causing the issue, which I also documented in the QGIS code. I agree with @agiudiceandrea this should be the way it works.

**Pull request merged**
