### PR TITLE
add matomo script and connect it with base template

### PR DESCRIPTION
**Pull request by Akiyamka**

### CODE REVIEW

**Comment by Xpirix** [comment]
Thank you for this work. I tested it locally but I assume that we need to connect to matomo.qgis.org to see if it works.

Besides, I have a few suggestions about the integration of matomo in QGIS-Django:
- I agree with @timlinux comments at https://github.com/kartoza/prj.app/pull/1452 to softcode the URL but also the SITE_ID into the site configuration.
- How about using [django-matomo](https://pypi.org/project/django-matomo/) since this website is based on Django? I noticed that this package is listed as an official Django integration and it's easier to manage the variables `MATOMO_SITE_ID ` and `MATOMO_URL` through the settings.py and the environments variables.

We could also ask @dimasciput about how the environment variables are in production.

**Comment by Akiyamka** [comment]
@Xpirix, thanks for the tip to use the plugin, seems like a good idea, I'll try to use it

**Comment by Xpirix** [comment]
Hello @Akiyamka , I've checked it locally and had the same error too. Adding `matomo` to the `INSTALLED_APPS` in `settings_docker.py` fixed the error. This is because django is using this file for docker environment. But I think other settings files need also to be updated to avoid the error in different environments.

**Comment by Xpirix** [comment]
Looks good to me. Thank you @Akiyamka.

**Comment by timlinux** [comment]
@dimasciput can you review, merge deploy please?

**Review by dimasciput — APPROVED** [review]

**Comment by dimasciput** [comment]
@timlinux @Xpirix before deploying this we probably might need to update the privacy policy.

**Comment by timlinux** [comment]
@dimasciput can you link to the policy in question?

**Pull request merged**
