### PR TITLE
API for discovering resources

### PR DESCRIPTION
**Pull request by sumandari**
This PR refers to #155. It provides API for discovering resources.

## Listing

result:
- resource_type
- resource_subtype
- id
- name
- creator
- upload_date
- download_count
- description
- file
- thumbnail

image

## List with Filter:

-  resource type (symbol / project / composition etc)
-  resource subtype (line symbol etc.)
-  keywords for search (e.g. 'Elevation') - should be case insensitive
-  creator

image

## Download resource in a zipfile

image

### CODE REVIEW

**Comment by timlinux** [comment]
As discussed today, resource_type and type seem redundant, we can remove one of them:

image

**Comment by timlinux** [comment]
Just other point of review:

I think we should use UUIDs for resources so that we can ask for a resource by UUID without needing then to give an ID and a type to specify what we want to get.

e.g. ap1/v1/style/1 becomes ap1/v1/resource/hjhkj88798732

**Comment by sumandari** [comment]
### Listing

- remove `highest_count` and `total_count` and replace it with `total`
- replace `id` with `uuid`

image

### Download

- use `uuid` instead of `id`

image

**Comment by timlinux** [comment]
LGTM

**Pull request merged**
