### PR TITLE
QLR sharing file feature

### PR DESCRIPTION
**Pull request by sumandari**
Please see #212 
- [x] CRUD
- [x] validation
- [x] parse url dataresource from .qlr
- [x] parse provider from .qlr
- [x] find out the license applied for the uploaded .qlr : free text license
- [x] add unit test for validation
- [x] add unit test for view
- [x] create license.txt file from license field in model
- [x] update download zipfile to include custom license.txt created

### CODE REVIEW

**Comment by sumandari** [comment]
image

**Comment by sumandari** [comment]
## Review page:
image



## Detail page
image

**Comment by sumandari** [comment]
Update menu and tiltle (#220), add url_metadata field and update license to not use cc0 rather the License of the resource itself
image

License from downloaded file is generated from license field value.
image

**Comment by timlinux** [comment]
LGTM thanks!

**Pull request merged**
