### PR TITLE
Add support for JSON-RPC plugin uploads

### PR DESCRIPTION
**Pull request by komima**
Fix for issue https://github.com/qgis/QGIS-Django/issues/265

### CODE REVIEW

**Comment by komima** [comment]
It seems the `devweb` container failed to start in the test workflow, I'll investigate more with local containers.

**Comment by komima** [comment]
https://github.com/celery/celery/issues/7783#issuecomment-1265269210

New version was causing the `worker` to fail on start, and `devweb` depending on it failing to start (hanging) as well, it seems pinning the version in the docker `REQUIREMENTS.txt` works.

**Comment by dimasciput** [comment]
hi @komima, this has been deployed to plugins.qgis.org

**Comment by komima** [comment]
@dimasciput the update worked great last week for plugin upload in our CI pipeline, but now it seems the deployment has been rolled back to a previous version without this fix, do you know why that might happen?

**Comment by dimasciput** [comment]
@komima can you give it another try?

**Pull request merged**
