### PR TITLE
so people don't press login while trying to search

### PR DESCRIPTION
**Pull request by jayenashar**
and subsequently request an OSGeo LDAP account

closes #159 #160

### CODE REVIEW

**Comment by jayenashar** [comment]
header on desktop:

image

page on mobile:

Screen Shot 2022-03-08 at 11 51 50

**Comment by jayenashar** [comment]
@jef-n thanks for merging.  how soon can we get this deployed?  requests for osgeo accounts to download plugins are still coming regularly.

**Comment by dimasciput** [comment]
@jayenashar it is deployed now.

**Comment by anitagraser** [comment]
Due to the size of the search button, certain window widths will cause the header to overflow into a second row and cover up the main content:

image

On a related note: in night mode, the menu icon is black on dark background: 

image

**Pull request merged**
