### PR TITLE
Add support for renaming plugin name

### PR DESCRIPTION
**Pull request by Xpirix**
- #270 
- #271 

Please find in [here](https://github.com/qgis/QGIS-Django/pull/271#issuecomment-1794858448) the details for this PR

### CODE REVIEW

**Comment by dimasciput** [comment]
Hi @Xpirix , can you add unit tests please?

**Comment by PeterPetrik** [comment]
thanks, Hard for me to understand the PR, but in case we can have new name set and upload new version of the plugin that will not override this new name I am fine :)

**Comment by Xpirix** [comment]
That's right. The new name will not change until the admin allows to read it from `metadata.txt` (Not allowed by default). So, the name value in the `metadata.txt` should be updated according to the new name.

**Comment by Xpirix** [comment]
Hi @dimasciput , Thank you for reminding me. I've added unit testing for the plugin's rename feature.

**Comment by PeterPetrik** [comment]
> That's right. The new name will not change until the admin allows to read it from `metadata.txt` (Not allowed by default). So, the name value in the `metadata.txt` should be updated according to the new name.

So for me as plugin admin, what steps I need to do to update plugin visible name? I am bit confused

**Comment by Xpirix** [comment]
> So for me as plugin admin, what steps I need to do to update plugin visible name? I am bit confused

Apologies for omitting the details in my previous message. Please refer to the screenshot and steps below for guidance on renaming a plugin via the administration page:




### Plugin Renaming in the Administration Page

1. Navigate to the plugin of interest from the plugins list.
2. Access the plugin details and modify the name field.
3. Save the changes to reflect the updated name in both QGIS and on the plugins website.

### Renaming a Plugin in a New Version

When an admin/owner uploads a new version with a name that doesn't match the existing one, an error will be triggered. To override this restriction, administrators can enable the "Allow Update Name" option by checking the corresponding checkbox as mentionned [here](https://github.com/qgis/QGIS-Django/pull/271#issuecomment-1794858448).

**Comment by PeterPetrik** [comment]
> When an admin/owner uploads a new version with a name that doesn't match the existing one, an error will be triggered.

This is what I do not understand: as a plugin developer, I thought `name` entry in `metadata-txt` should stay as the old plugin name, right? see https://docs.qgis.org/3.28/en/docs/pyqgis_developer_cookbook/plugins/plugins.html#metadata-txt

**Comment by Xpirix** [comment]
You are absolutely right. Thanks for the feedbak.

I just fixed that. There is no more error when you upload a plugin zip with the old name that is different form the new name. These process are correct:

> as plugin developer
> 1. I ask super-admin to change plugin name for me in the administrator page
> 2. I can still upload my plugin zip via interface without any modification (== with old name)
> 3. And my plugin will show the "new" name in QGIS install + web interface

**Comment by PeterPetrik** [comment]
👏

**Comment by PeterPetrik** [comment]
Great, let me know when this is released, so we can fix the name of Mergin plugin. Thanks!

**Comment by Xpirix** [comment]
@PeterPetrik Sure, we will let you know when this is released.

**Comment by Xpirix** [comment]
Dear @PeterPetrik, these changes are now released on the plugin website.

**Comment by PeterPetrik** [comment]
Very good, thanks

**Comment by Xpirix** [comment]
My pleasure.

**Pull request merged**
