### PR TITLE
Add token based authentication feature

### PR DESCRIPTION
**Pull request by Xpirix**
- This PR addressing the issue #68 

## Changes Summary

- Install and add `pyjwt` and `djangorestframework-simplejwt` in the requirements files.
- Specify token validity in the settings: 15 days for access and 180 days for refresh.
- Add token creation (`/api/token/`) and refresh (`/api/token/refresh/`) endpoints.
- Implement the token-based authentication system, which does not impact the existing authentication system. Token-based authentication will only be used if `Bearer the_access_token` is specified in `HTTP_AUTHORIZATION`. The process involves:
  1. Check if the value of `HTTP_AUTHORIZATION` starts with `Bearer`.
  2. Validate the token.
  3. Get the user based on the validated token.
  4. Log in and allow the request.
- Update the README for this feature.

Please find below a video demonstrating this feature in Postman. In this example, we specify the token in the GET request, and the cookies are set automatically. Thus, there's no need to specify the token in the POST request.

https://github.com/qgis/QGIS-Django/assets/43842786/dc49d70c-a49d-44a3-9e50-0852b52be15f

### CODE REVIEW

**Comment by m-kuhn** [comment]
Thank you very much. 🎉
Could you show a screenshot of the plugin config page, where plugin maintainers can manage tokens for specific plugins?

**Comment by Xpirix** [comment]
@m-kuhn My pleasure.

I've made some changes to make specific tokens for plugin, not only for authentication. Please find below the updated description for this PR.

## Changes Summary

- Integrate `pyjwt` and `djangorestframework-simplejwt` into the project's requirements files.
- Configure token validity settings: 15 days for both access and refresh tokens.
- Introduce a new `Tokens` button in the plugin management tab, facilitating redirection to the Token Management page.
- Implement a functionality to generate a specific token tied to the current plugin and the authenticated user.
- Display a list of available tokens, showcasing only those associated with the authenticated user and the corresponding plugin. Clicking on a token will redirect to the Token Details page.
- Integrate a button for token deletion.

## Token Usage Guidelines

- Utilize a token for uploading or updating a plugin version via the following URLs:
  - `https://plugins.qgis.org/plugins/api/<package_name>/version/add/`
  - `https://plugins.qgis.org/plugins/api/<package_name>/version/<version>/update`
  
- Tokens are exclusively valid for the specific plugin with which they are associated.
- Tokens automatically become invalid upon deletion or upon reaching the expiration date.

Please find below a GIF demonstrating this feature.

Token_auth

**Comment by m-kuhn** [comment]
Thanks for the update @Xpirix , this new screencast looks very promising!

If I understand correctly, there is a timeout on the token of 15 days and the token needs to be refreshed?
The most typical use case I can think of is storing the token as a github secret and then creating CI/CD automations that make use of this token. There is no logic running, that could regularly refresh such a token and store a refreshed token (secrets are manually managed). Ideally I was thinking to acquire a token once and then have it available forever.

Additional ideas more "nice to have":

 - Show the token only once on the user interface and then hide it
 - Show when the token was last used
 - Ability to give a description to a token (so I can flag it as my "github action" token or "mkuhn local test" token or similar)

One example: https://help.transifex.com/en/articles/6248858-generating-an-api-token (even though this is linked to the user account like a personal access token rather than a resource specific token as here). Other similar examples would be "github repository deploy key" with the difference that this key is not generated, but the rest is very much the same.

I am also interested in opinions from @Gustry @Guts @3nids as qgis-plugin-ci contributors/maintainers

**Comment by m-kuhn** [comment]
One more thing 

> showcasing only those associated with the authenticated user and the corresponding plugin

as a plugin maintainer I would like to see all tokens that are associated with a plugin I am responsible for, even if they were generated by others in the team. I think it's nice to _show_ who created a token but a token should be completely detached from a user account after creation. I.e. if a someone leaves the development team, the token should be kept active, so any CI/CD pipelines continue to work and others in the team should then still be able to revoke this token.

**Comment by Xpirix** [comment]
Thank you for the feedback @m-kuhn .

>If I understand correctly, there is a timeout on the token of 15 days and the token needs to be refreshed?
>The most typical use case I can think of is storing the token as a github secret and then creating CI/CD automations that make use of this token. There is no logic running, that could regularly refresh such a token and store a refreshed token (secrets are manually managed). Ideally I was thinking to acquire a token once and then have it available forever.

Yes, that makes sense. I will make every token available forever. They can always be revoked anytime.

>Additional ideas more "nice to have":
>- Show the token only once on the user interface and then hide it
>- Show when the token was last used
>- Ability to give a description to a token (so I can flag it as my "github action" token or "mkuhn local test" token or similar)

Thanks for theses ideas, I'm going to implement them.

>as a plugin maintainer I would like to see all tokens that are associated with a plugin I am responsible for, even if they were generated by others in the team.

That's well noted.

>I think it's nice to show who created a token but a token should be completely detached from a user account after creation. I.e. if a someone leaves the development team, the token should be kept active, so any CI/CD pipelines continue to work and others in the team should then still be able to revoke this token.

From what I understand from the basic process of uploading/updating a plugin version, a user is always needed. Indeed, a token contains the plugin information but also the user identity (user_id) because the user don't have to log in when using it. If we don't store the user identity in the token, we won't be able to retreive which user is uploading a plugin and the process will raise an error.

image

**Comment by m-kuhn** [comment]
Thank you for these updates.

> If we don't store the user identity in the token, we won't be able to retreive which user is uploading a plugin and the process will raise an error.

One question regarding this, if Anna creates a token for FancyPlugin and configures a release pipeline to use this token (e.g. stored in github action secrets). Later Anna leaves the dev team and removed permissions to upload new versions. If a new release is triggered via this pipeline, will the pipeline still work?

**Comment by Xpirix** [comment]
@m-kuhn You're welcome.

> One question regarding this, if Anna creates a token for FancyPlugin and configures a release pipeline to use this token (e.g. stored in github action secrets). Later Anna leaves the dev team and removed permissions to upload new versions. If a new release is triggered via this pipeline, will the pipeline still work?

I see. You're right; the pipeline will not work anymore because this Token contains the user information, and Anna doesn't have the permission anymore.

To resolve this, I will edit the workflow when uploading a new version using a token:

- If a token is specified, do not check for the user or the user's permission.
- Check if the token is valid and is connected to the plugin.
- Upload/update the plugin version.
- Set the column **Uploaded by** to CI/CD pipeline. This will involve editing the model `PluginVersion` by adding a new column `is_from_pipeline` and setting the column `created_by` to nullable.

This way, all created tokens will be independent from Anna, and the pipeline will continue to work even if Anna leaves the dev team and no longer has the permission.

image

**Comment by m-kuhn** [comment]
I like this. Alternative to the current term: " Token {token_description}"? But it's a tiny detail, only if it's reasonable effort.

**Comment by Xpirix** [comment]
I've made the updates. Each created token is now independent from the user who created it. 

> Alternative to the current term: " Token {token_description}"?

Please find below the screenshot for the Uploaded by column for this.

image

**Review by dimasciput — APPROVED** [review]

**Comment by Xpirix** [comment]
This feature has been deployed. Please feel free to check and share your feedback.

Thanks.

**Comment by m-kuhn** [comment]
Cool, what can I do with the Jti ?

image

**Comment by Xpirix** [comment]
I think it's something like an ID for the token. But we can hide that since we implemented the Description column.

**Pull request merged**
