### PR TITLE
Add Feature [276] Plugins feedback (multiple tasks)

### PR DESCRIPTION
**Pull request by sumandari**
This is to address #276 and https://github.com/qgis/QGIS-Django/pull/281#issuecomment-1586978519

- [x] create a feedback model
- [x] create query manager model
- [x] create POST create new feedback
- [x] notify user when feedback created
- [x] implement `- [ ]` to create multiple tasks
- [x] create GET feedback - should show previous comment with check button and delete button
- [x] update feedback/task to complete/incomplete - allow plugin editors and staff
- [x] delete feedback - only allow ~~staff~~ reviewer (staff that submitted feedback) to delete feedback
- [x] show "feedback received" and "feedback pending" on staff left navbar

https://github.com/qgis/QGIS-Django/assets/40058076/1abfe1f0-f408-43a8-ba77-c8383c681adc

### CODE REVIEW

**Comment by sumandari** [comment]
## staff
https://github.com/qgis/QGIS-Django/assets/40058076/1fab8f16-8bf5-4c64-93d2-f6f9e5e73f5b

---
## plugin editor


https://github.com/qgis/QGIS-Django/assets/40058076/db51165f-896c-492c-bb2b-5e51f65a2c4f

**Comment by dimasciput** [comment]
Awesome job @sumandari , I will test this.

**Comment by dimasciput** [comment]
@sumandari thanks, I have tested this, it works well but the checkbox is not very clear. 
Perhaps we could add some explanatory text to the page and include a submit button? Once clicked, this button could disable any checked boxes to prevent unticking. Adding a confirmation prompt when you click submit might also be beneficial.

**Comment by dimasciput** [comment]
Something like this

image

**Comment by sumandari** [comment]
Thanks @dimasciput, that makes sense. I will update it with a submit button. 
and a pop up info on the checkboxes (or.. what element could be better?)
But btw, unticking is in purpose solution. Just in case reviewer/ owner regretted ticking it. 😬
Do you think it’s better to prevent unticking boxes?

**Comment by dimasciput** [comment]
@sumandari 
> Do you think it’s better to prevent unticking boxes?

I think this should be fine and easier to implement.

**Comment by sumandari** [comment]
@dimasciput I updated the PR with;
- explanatory text
- submit button
- unticking prevention
- enable/disable the update button



https://github.com/qgis/QGIS-Django/assets/40058076/bdb6273e-869c-4c38-b74c-d30954629662

**Comment by dimasciput** [comment]
@sumandari awesome changes, I will test this later.

**Comment by dimasciput** [comment]
@Xpirix can you test this PR please

**Comment by Xpirix** [comment]
@dimasciput @sumandari , This is a great feature. I tested and it works well on both staff and plugin creator side. Unticking and updating button management work fine as well.

However, is there any character limit when submiting a new feedback? I tryed with lorem*20 and it worked.
When no feedback has been submitted, I think it's better to hide the explantory text and notify that there is no feedback.

**Pull request merged**
