### PR TITLE
Improve members section in QGIS Plugin repository site

### PR DESCRIPTION
**Pull request by GeoSander**
This improves the readability of the "SUSTAINABLE MEMBERS" header at the bottom of the QGIS Plugin repository pages, and also enhances the appearance of the GeoCat and Midvatten logos (at the bottom) against dark backgrounds.

Before/current:
image

After:
image

### CODE REVIEW

**Comment by GeoSander** [comment]
Hi @Xpirix, thanks for reviewing.

Happy to hear that the plugins page will soon match the appearance of the new the main QGIS homepage, including its sustainable members section.

When do you expect that it will be released?

Sander

**Comment by Xpirix** [comment]
Hi @GeoSander,

I will continue working on some fixes and also apply the branding to the Resources Hub (Styles, geopackages...) and the planet website in the next few months. They should be released before the end of the year.

Regards.

**Comment by GeoSander** [comment]
Alright, all the best finalizing your work then!

Until that time, merging this PR will not break anything 😜 
But I'll let it rest 😁

**Comment by Xpirix** [comment]
Thank you. 
I'm merging it as a fix for the current website version, then.

**Comment by GeoSander** [comment]
Thanks so much 🙏☺️

**Pull request merged**
