### PR TITLE
Fix #10126 Use NGramField to allow searching partial terms.

### PR DESCRIPTION
**Pull request by akbargumbira**
Hi @elpaso, @pcav, @timlinux, this will fix http://hub.qgis.org/issues/10126 to allow searching partial terms. We need to update or rebuild the index again though.

### CODE REVIEW

**Comment by elpaso** [comment]
Thanks for the PR, will this require a DB migration or is it the same DB field type? (we are using postgresql)

**Comment by akbargumbira** [comment]
No, it's from the haystack (with whoosh engine) and saved in the filesystem. We just need to update the index. I am not sure though how we keep the index fresh in the production (using a cron job or other method)

**Comment by akbargumbira** [comment]
@elpaso btw I haven't seen the effect of the merge. Has it been deployed to the production? If it has, to make it work, we need to update/rebuild the index by running ```python manage.py rebuild_index```. Thanks

**Comment by elpaso** [comment]
@pcav, @timlinux, @akbargumbira deployed all your merged PRs

**Comment by elpaso** [comment]
@pcav, @timlinux, @akbargumbira reverting because of errors. Please fix it then deploy it yourself.

**Comment by akbargumbira** [comment]
@elpaso hi, how could I replicate the error? Did you rebuild the haystack index again after deploying it? And I don't have access to the server

**Comment by elpaso** [comment]
@akbargumbira sent you a pm on gmail, I've fixed it anyway with https://github.com/qgis/QGIS-Django/commit/8338f9c0f406da3dd3866395c8c6c352aaafa40f

**Pull request merged**
