### PR TITLE
Add Layer Definition File and 3D Model to the resource API

### PR DESCRIPTION
**Pull request by Xpirix**
This is a proposed change for #280 

## Changes summary

- Return Layer Definition and Wavefront (3D Model) in the resource API
- Update unit test

image

### CODE REVIEW

**Comment by ismailsunni** [comment]
So, Wafefront is the 3D model? May I know why is it called like that? Otherwise, it looks good for me

**Comment by Xpirix** [comment]
I think it refers to the pip package the app used to manage 3D models which is called `PyWavefront`. It's related to #182.

**Comment by ismailsunni** [comment]
@Xpirix perhaps, it's better to have different terminology for the resource type since it's not self explanatory. It is also more on the technical term, not the context. See similar comment regarding this https://github.com/qgis/QGIS-Django/pull/202#issuecomment-947421398. I guess `3DModel` is clearer.

**Comment by Xpirix** [comment]
Yes, that makes more sense. I've changed Wavefront to 3DModel for the resource API for now. Also, I will create an issue to replace all Wavefront occurrences in the code with 3DModel.

image

**Comment by ismailsunni** [comment]
Thanks @Xpirix !

**Review by dimasciput — APPROVED** [review]

**Comment by ismailsunni** [comment]
thanks lord @dimasciput

**Pull request merged**
