### PR TITLE
add metadata option for support of Python 3

### PR DESCRIPTION
**Pull request by 3nids**

### CODE REVIEW

**Comment by elpaso** [comment]
Thanks! Did you also change the `models.py`? This requires a DB change (migration) to add the new field.

**Comment by 3nids** [comment]
done.
I am not really sure if I did things properly, I have no idea what's going on behind!

**Comment by timlinux** [comment]
I think this may be redundant since @elpaso and @dimasciput have migrated to python 3. @sumandari please review and close or discuss with me if we will implement something.

**Comment by sumandari** [comment]
yes @timlinux,  the code are mostly redundant with current master branch. The difference is it adds `support_python3` field on the plugins models. I'm not sure if we will implement it.
https://github.com/qgis/QGIS-Django/blob/7ae159c0058491354166123c25396907278354e8/qgis-app/plugins/models.py#L456

**Comment by timlinux** [comment]
I think we just close this @3nids since the platform is already set up with Python3 plugin support etc. and python 2 is becoming a distant memory. Please reopen if you think we still need this.

**Pull request closed without merging**
