### PR TITLE
check url link in metadata plugins

### PR DESCRIPTION
**Pull request by sumandari**
This PR refers to #117.

Error will raise when metadata contains one of these:

- tracker=http://bugs
- repository=http://repo
- homepage=http://homepage

---
Error raised when uploading the plugin

image

### CODE REVIEW

**Review by Gustry — COMMENTED** [review]
Thanks @sumandari for this work ! (and @timlinux )

Have you checked a more generic URL test : 
https://stackoverflow.com/a/38020041/2395485

**Comment by sumandari** [comment]
Thanks for your advise @Gustry.
I added the urlparsing check and check if the web exists by retrieve the status_code from header. But it will slow down the upload process. Do you think it's necessary to do that check (status_code check)?

**Comment by timlinux** [comment]
> Thanks for your advise @Gustry.
> I added the urlparsing check as you mentioned it.
> 
> And also add check if the web exists by retrieve the status_code from header. But it will slow down the upload process. Do you think it's necessary to do that check (status_code check)?

So I think it is good to check we get a valid status code for all the urls provided, so thanks for adding that.

**Comment by timlinux** [comment]
LGTM

**Review by Gustry — APPROVED** [review]
LGTM, thanks for updating the situation here !

**Pull request merged**
