### PR TITLE
generate plugins xml for qgis 3.18 and 3.19

### PR DESCRIPTION
**Pull request by kannes**

### CODE REVIEW

**Review by sumandari — APPROVED** [review]

**Comment by sumandari** [comment]
Thanks @kannes

**Comment by Gustry** [comment]
The need to update this file for every release looks not something future proof. I think it could be nice we could avoid this.

What happened if we had more versions from future now ? Will it be OK ?
Maybe, the best, can we make this list optional? With a default value to 3.99 ? What is-it used for ?

Sorry, I haven't checked the code.

**Comment by agiudiceandrea** [comment]
When will the fix be "online"?
Both https://plugins.qgis.org/plugins/plugins.xml?qgis=3.18 and https://plugins.qgis.org/plugins/plugins.xml?qgis=3.19 return:
404 Not Found

**Comment by sumandari** [comment]
It's scheduled to be deployed today, @agiudiceandrea.

/cc @dimasciput

**Comment by sumandari** [comment]
@agiudiceandrea the fix is now live.

> Both https://plugins.qgis.org/plugins/plugins.xml?qgis=3.18 and https://plugins.qgis.org/plugins/plugins.xml?qgis=3.19

**Comment by kannes** [comment]
Thanks!

@Gustry I agree, maybe it should be handled by QGIS itself while the site throws all available plugins for any version at it? Probably best to move into a new issue, here it would be lost.

**Pull request merged**
